def game_utama():
    print("--- MEMULAI PETUALANGAN DIGITAL ---")
    nama = input("Siapa namamu? ")
    
    print(f"\n🏝️  Selamat datang, {nama}!")
    print("=" * 50)
    print("\nAnda terbangun di sebuah pulau misterius yang penuh dengan hutan lebat.")
    print("Suara-suara aneh terdengar dari kejauhan... itu adalah orang-orang kanibal!")
    print("Anda harus menemukan cara untuk melarikan diri dari pulau yang menakutkan ini.")
    print("\n" + "=" * 50)
    print("\n⚠️  PILIHAN JALUR ESCAPE ⚠️")
    print("1. Membuat Perahu Coding - Kumpulkan kayu dan buat perahu dengan teknik coding")
    print("2. Berenang Bug - Cepat-cepat berenang meninggalkan pulau sebelum ketahuan")
    print("3. Menjelajahi Pulau - Cari harta karun dan sumber daya tersembunyi")
    
    pilihan = input("\nPilihan Anda (1, 2, atau 3): ")
    
    if pilihan == "1":
        print("\n" + "=" * 50)
        print("🛠️  JALUR: MEMBUAT PERAHU CODING")
        print("=" * 50)
        print(f"\n{nama} memutuskan untuk membuat perahu menggunakan kekuatan coding...")
        print("✔️  Mengumpulkan kayu dari hutan...")
        print("✔️  Menulis algoritma konstruksi...")
        print("✔️  Menggunakan Python untuk menghitung struktur yang kuat...")
        print(f"\n🎉 Berhasil! Perahu {nama} selesai dibuat dengan sempurna!")
        print("⛵ Anda berlayar menjauh dari pulau berbahaya ini.")
        print("\n✅ SELAMAT! Anda berhasil melarikan diri dengan perahu yang kokoh!")
        print(f"   {nama} telah menyelamatkan diri dari pulau kanibal! 🎊")
        
    elif pilihan == "2":
        print("\n" + "=" * 50)
        print("🏊 JALUR: BERENANG BUG")
        print("=" * 50)
        print(f"\n{nama} memutuskan untuk segera berenang meninggalkan pulau...")
        print("⚡ Berlari cepat ke tepi pantai...")
        print("🌊 Melompat ke laut dan mulai berenang dengan kencang...")
        print("👀 Mendengar suara kaki orang kanibal di belakang...")
        print("💨 Berenang semakin cepat meninggalkan pulau...")
        print("\n🎉 Berhasil! Anda lolos!!")
        print("🏊 Anda terapung di laut dan ditemukan oleh kapal penyelamat!")
        print("\n✅ SELAMAT! Anda berhasil melarikan diri dengan cepat!")
        print(f"   {nama} telah selamat dari pulau kanibal! 🎊")
        
    elif pilihan == "3":
        print("\n" + "=" * 50)
        print("🗺️  JALUR: MENJELAJAHI PULAU")
        print("=" * 50)
        print(f"\n{nama} memutuskan untuk menjelajahi pulau dan mencari sumber daya berharga...")
        print("\n🔦 Berjalan menembus hutan yang lebat dengan hati-hati...")
        print("🌴 Pohon-pohon tinggi menghalangi cahaya matahari...")
        print("🦗 Suara-suara aneh dan mencurigakan terdengar di sekitar...")
        
        print("\n" + "!" * 50)
        print("⚠️  PERHATIAN! ORANG KANIBAL DITEMUKAN!")
        print("!" * 50)
        print(f"\nTiba-tiba, {nama} melihat sekelompok orang kanibal berjalan mendekati!")
        print("👥 Ada 5 orang kanibal dengan senjata primitif!")
        print("🔥 Mereka menyalakan api dan membuat keributan...")
        print("😱 Mereka belum melihat Anda... tapi akan segera!")
        
        print("\n⚡ PILIHAN AKSI CEPAT:")
        print("1. Bersembunyi di balik pohon besar - Tunggu sambil mencuri lewat")
        print("2. Bernegosiasi - Coba berbicara dengan mereka")
        print("3. Mengalihkan perhatian - Lempar batu ke arah lain")
        print("4. Berlari menuju tempat aman - Cepat-cepat kabur tanpa arah yang pasti")
        
        aksi = input("\nPilihan aksi Anda (1, 2, 3, atau 4): ")
        
        if aksi == "1":
            print(f"\n{nama} dengan cepat bersembunyi di balik pohon yang sangat besar...")
            print("🤫 Taktik sembunyi dijalankan dengan sempurna!")
            print("✔️  Orang kanibal lewat tanpa menyadari kehadiran Anda...")
            print("✔️  Menunggu sampai mereka jauh...")
            print("\n🎉 Berhasil lolos tanpa diketahui!")
            print("📍 Sekarang saatnya lanjut eksplorasi gua...")
            
            print("\n🔦 Melanjutkan perjalanan, sampai di gua misterius!")
            print("\n⭐ PILIHAN EKSPLORASI:")
            print("a. Masuk ke dalam gua - Mungkin ada harta karun!")
            print("b. Mendengarkan suara dari gua - Terdengar seperti air terjun!")
            
            sub_pilihan = input("\nPilihan eksplorasi Anda (a atau b): ")
            
            if sub_pilihan == "a":
                print(f"\n{nama} berani masuk ke dalam gua yang gelap...")
                print("✔️  Menyalakan api untuk menerangi gua...")
                print("💎 Menemukan harta karun: emas, permata, dan peta harta!")
                print("📜 Peta menunjukkan lokasi perahu pelarian yang sudah siap!")
                print("\n🎉 Jackpot! Semua yang " + nama + " butuhkan ada di gua!")
                print("⛵ Mengikuti peta dan menemukan perahu yang sudah dilengkapi makanan!")
                print("\n✅ SELAMAT! Anda berhasil melarikan diri dengan harta karun!")
                print(f"   {nama} lolos dari kanibal dan kaya raya! 💰🎊")
            elif sub_pilihan == "b":
                print(f"\n{nama} mengikuti suara air terjun ke dalam gua...")
                print("💧 Menemukan air tawar yang jernih!")
                print("🐠 Kolam ikan besar penuh dengan makanan lezat!")
                print("✔️  Mengumpulkan makanan dan air tawar untuk perjalanan...")
                print("🎒 Bersiap dengan perbekalan yang cukup...")
                print("🌳 Kembali keluar dan menemukan pohon kelapa yang penuh buah!")
                print("🛠️  Menggunakan kelapa untuk membuat tali dan kayu untuk perahu buatan!")
                print("\n🎉 Berhasil! Perahu sederhana tapi kuat berhasil dibuat!")
                print("⛵ Berlayar dengan penuh semangat meninggalkan pulau berbahaya!")
                print("\n✅ SELAMAT! Anda berhasil survive dan melarikan diri!")
                print(f"   {nama} keluar dari pulau dengan strategi jitu! 🎊")
            else:
                print("\n❌ Pilihan eksplorasi tidak valid!")
                print(f"   {nama} tidak berhasil melarikan diri. GAME OVER! 💀")
                
        elif aksi == "2":
            print(f"\n{nama} dengan berani keluar dan mencoba berbicara dengan mereka...")
            print("🗣️  Memberanikan diri untuk bernegosiasi...")
            print("💬 Menceritakan bahwa Anda adalah orang asing yang tersesat...")
            print("😮 Pemimpin kanibal terkejut mendengar cerita Anda!")
            print("🤝 Mereka percaya dan justru membantu memberikan makanan!")
            print("💝 Pemimpin kanibal memberikan peta rahasia mereka!")
            print("📜 Peta menunjukkan perahu pelarian di tempat tersembunyi!")
            print("\n🎉 Negoisasi berhasil! Anda mendapat bantuan tak terduga!")
            print("⛵ Menggunakan peta dan perbekalan dari kanibal untuk berlayar!")
            print("\n✅ SELAMAT! Anda berhasil melarikan diri dengan bantuan!")
            print(f"   {nama} membuat hubungan baik dan selamat dari pulau! 🎊")
            
        elif aksi == "3":
            print(f"\n{nama} dengan cepat mengambil beberapa batu dan melemparkannya...")
            print("💨 Melempar batu ke arah yang berlawanan dengan jalan Anda...")
            print("💥 Ledakan suara membuat orang kanibal bingung dan bergerak menjauh!")
            print("⚡ Anda memanfaatkan kesempatan untuk lari ke arah gua!")
            print("🏃 Berlari secepat mungkin meninggalkan area...")
            print("✔️  Mencapai gua dengan aman!")
            
            print("\n🔦 Sekarang Anda aman di dalam gua!")
            print("\n⭐ PILIHAN EKSPLORASI:")
            print("a. Masuk lebih dalam gua - Mungkin ada harta karun!")
            print("b. Istirahat dan mencari sumber air - Cari air tawar!")
            
            sub_pilihan = input("\nPilihan eksplorasi Anda (a atau b): ")
            
            if sub_pilihan == "a":
                print(f"\n{nama} terus masuk ke dalam gua...")
                print("✔️  Menyalakan api untuk menerangi jalan...")
                print("💎 Menemukan harta karun: emas, permata, dan senjata!")
                print("⚔️  Ada juga blueprint perahu modern dalam gua!")
                print("\n🎉 Jackpot! Peralatan lengkap untuk melarikan diri!")
                print("🛠️  Membuat perahu pakai blueprint yang ditemukan...")
                print("⛵ Perahu siap dan berlayar dengan percaya diri!")
                print("\n✅ SELAMAT! Anda berhasil melarikan diri dengan harta karun!")
                print(f"   {nama} kaya raya dan selamat dari pulau kanibal! 💰🎊")
            elif sub_pilihan == "b":
                print(f"\n{nama} mencari sumber air dalam gua...")
                print("💧 Menemukan air terjun yang indah dalam gua!")
                print("🌊 Ada kolam air tawar yang besar...")
                print("🐠 Banyak ikan untuk dimakan...")
                print("✔️  Mengumpulkan perbekalan dan istirahat di gua...")
                print("🌳 Keluar dan menemukan pohon buah-buahan!")
                print("🛠️  Menggunakan bahan-bahan untuk membuat perahu sederhana!")
                print("\n🎉 Perahu buatan sendiri berhasil dibuat!")
                print("⛵ Berlayar dengan cepat ke tempat aman!")
                print("\n✅ SELAMAT! Anda berhasil survive dan melarikan diri!")
                print(f"   {nama} keluar dari pulau dengan strategi pintar! 🎊")
            else:
                print("\n❌ Pilihan eksplorasi tidak valid!")
                print(f"   {nama} tertangkap kanibal. GAME OVER! 💀")
                
        elif aksi == "4":
            print(f"\n{nama} merasa panik dan mulai berlari dengan cepat!")
            print("🏃 Berlari secepat kaki membawa, tidak peduli arah tujuan!")
            print("❌ Suara kanibal semakin mendekat...")
            print("🌳 Menembus semak-semak dan pohon-pohon yang lebat...")
            print("💨 Jantung berdebar... napas memburu... kaki semakin cepat...")
            print("😰 Terdengar suara genderang dan jeritan kanibal di belakang!")
            
            print(f"\n🔍 Dalam kepanikan, {nama} melihat beberapa tempat tersembunyi:")
            print("a. Gua kecil di tepi tebing - Gelap dan berbahaya!")
            print("b. Lubang pohon besar di akar - Sempit tapi aman!")
            print("c. Kolam air dengan rawa - Basah tapi bisa menyeberangi!")
            
            tempat_sembunyi = input("\nMana tempat aman yang akan Anda pilih (a, b, atau c)? ")
            
            if tempat_sembunyi == "a":
                print(f"\n{nama} memasuki gua kecil dengan tergesa-gesa...")
                print("🌑 Gelap sekali... tidak bisa melihat apa-apa...")
                print("🦇 Suara kelelawar dan binatang aneh terdengar...")
                print("😨 Rasanya seperti ada sesuatu di dalam gua ini...")
                print(f"✔️  Tapi pantas saja... {nama} tetap diam dan tenang!")
                print("🤐 Menahan napas sambil mendengarkan suara kanibal lewat...")
                print("✔️  Mereka berlalu tanpa menyadari kehadiran Anda!")
                print("💎 Setelah beberapa saat, mata mulai terbiasa dengan gelap...")
                print("✨ Ternyata ada benda berkilau di sudut gua!")
                print("💰 Harta karun tersembunyi - emas dan permata!")
                
                print("\n" + "=" * 50)
                print("⭐ KEPUTUSAN PENTING ⭐")
                print("=" * 50)
                print(f"\n{nama} sudah aman di gua ini. Sekarang harus mengambil keputusan:")
                print("1. Tetap di tempat persembunyian Coding - Gunakan sumber daya gua untuk bertahan")
                print("2. Melarikan diri Bug - Ambil harta karun dan langsung cari perahu!")
                print("3. Ragu-ragu tanpa keputusan - Menunggu tanpa rencana")
                
                keputusan_aman = input("\nKeputusan Anda (1, 2, atau 3): ")
                
                if keputusan_aman == "1":
                    print(f"\n{nama} memutuskan untuk tetap tinggal di gua dengan strategi coding...")
                    print("💻 Mulai memetakan sumber daya yang ada dalam gua...")
                    print("🔬 Menggunakan logika dan algoritma untuk bertahan lama...")
                    print("📝 Menulis catatan dan rencana escape dengan detail...")
                    print("🛠️  Memperkuat struktur gua dengan kayu dan batu...")
                    print("💧 Mencari air yang aman untuk diminum...")
                    print("🍖 Mempelajari pola kanibal dari jarak aman...")
                    print("\n✔️  Setelah berhari-hari bersabar dan merencanakan...")
                    print("📚 Rencana sempurna untuk escape akhirnya terbentuk!")
                    print("🎯 Menemukan celah waktu saat kanibal tidur...")
                    print("⛵ Menggunakan perahu tersembunyi yang ada dalam peta harta karun!")
                    print("\n✅ SELAMAT! Escape terkoordinasi dengan sempurna!")
                    print(f"   {nama} melarikan diri dengan harta karun! 💰🎊")
                    
                elif keputusan_aman == "2":
                    print(f"\n{nama} mengambil keputusan berani untuk segera melarikan diri...")
                    print("⚡ Mengambil harta karun dan semua yang bisa dibawa...")
                    print("🏃 Berlari keluar gua tanpa membuang waktu...")
                    print("🗺️  Mengikuti peta harta karun menuju lokasi perahu...")
                    print("😰 Mendengar suara kanibal mulai bangun...")
                    print("💨 Berlari semakin cepat meninggalkan area hutan...")
                    print("🌊 Mencapai pantai dan menemukan perahu tersembunyi!")
                    print("⛵ Cepat-cepat berlayar keluar sebelum kanibal tiba!")
                    print("\n🎉 Berhasil escape dengan harta dan kecepatan!")
                    print("😅 Napas lega - kanibal tertinggal jauh di belakang!")
                    print("\n✅ SELAMAT! Escape dengan harta dan nyawa selamat!")
                    print(f"   {nama} melarikan diri dengan cepat dan harta berharga! 💰🎊")
                    
                elif keputusan_aman == "3":
                    print(f"\n{nama} tidak bisa memutuskan apa-apa dan hanya diam saja di gua...")
                    print("⏳ Waktu terus berjalan... kanibal masih berkeliaran...")
                    print("😅 Makanan dalam gua mulai terbatas...")
                    print("💧 Air mulai habis karena tidak ada yang mengelola sumber daya...")
                    print("📉 Kekuatan fisik semakin melemah hari demi hari...")
                    print("😞 Rasa putus asa menyelimuti karena tidak ada rencana escape...")
                    print("🌑 Gelap hati dan gelap gua terasa lebih mencekam...")
                    print("😴 Akhirnya tertidur dalam keadaan yang sangat lemah...")
                    print("💤 Tidak bangun lagi karena kekurangan nutrisi dan dehidrasi...")
                    print("\n❌ GAME OVER! Kehabisan sumber daya!")
                    print(f"   {nama} meninggal karena tidak ada keputusan tepat. SELAMAT TINGGAL! 💀")
                    
                else:
                    print("\n❌ Keputusan tidak valid! Kanibal mendengar gerakan Anda!")
                    print(f"   {nama} gagal escape dari gua. GAME OVER! 💀")
                
            elif tempat_sembunyi == "b":
                print(f"\n{nama} melompat masuk ke lubang pohon besar!")
                print("🌳 Tangan menyentuh akar-akar pohon yang bergerak-gerak...")
                print("🐛 Berbagai serangga menemani di dalam lubang ini...")
                print("✔️  Meski sempit dan tidak nyaman, itu tempat yang sangat aman!")
                print("🤐 Tetap diam mendengarkan suara kanibal di atas...")
                print("👣 Langkah kaki kanibal lewat di atas kepala Anda...")
                print("😤 Menahan diri untuk tidak bersin atau batuk...")
                print("✔️  Akhirnya mereka lewat dan suara berkurang...")
                print("\n🌅 Setelah waktu lama, Anda keluar dari lubang pohon...")
                print("🎒 Menemukan makanan alami - buah-buahan dan air segar!")
                
                print("\n" + "=" * 50)
                print("⭐ KEPUTUSAN PENTING ⭐")
                print("=" * 50)
                print(f"\n{nama} sudah aman keluar dari lubang pohon. Sekarang harus mengambil keputusan:")
                print("1. Tetap di tempat persembunyian Coding - Bangun shelter dan tunggu situasi aman")
                print("2. Melarikan diri Bug - Langsung cari perahu dan tinggalkan pulau!")
                print("3. Ragu-ragu tanpa keputusan - Menunggu tanpa rencana")
                
                keputusan_aman2 = input("\nKeputusan Anda (1, 2, atau 3): ")
                
                if keputusan_aman2 == "1":
                    print(f"\n{nama} memutuskan untuk membangun shelter permanen di area pohon...")
                    print("🏠 Memanfaatkan lubang pohon sebagai tempat tinggal sementara...")
                    print("🛠️  Membuat struktur kayu yang kokoh dengan teknik coding nature...")
                    print("💧 Mengumpulkan air dari morning dew dan membuat reservoir...")
                    print("🍖 Mengatur sistem berburu ikan dan memasak dengan hati-hati...")
                    print("📊 Membuat jadwal harian untuk monitor pergerakan kanibal...")
                    print("🔍 Mengamati pola kelakuan kanibal selama berminggu-minggu...")
                    print("\n✔️  Akhirnya menemukan celah gap saat mereka holiday...")
                    print("🛠️  Membuat perahu dari kayu pohon dengan sempurna!")
                    print("⛵ Berlayar keluar dengan persiapan yang matang!")
                    print("\n✅ SELAMAT! Persiapan detail membuat escape sempurna!")
                    print(f"   {nama} escape dengan strategi terencana! 🎊")
                    
                elif keputusan_aman2 == "2":
                    print(f"\n{nama} tidak mau menunggu lagi dan langsung mencari perahu...")
                    print("🏃 Berlari ringan menuju pantai sambil menghindari jalur kanibal...")
                    print("🗺️  Mengikuti tanda-tanda alam yang menunjukkan arah laut...")
                    print("😰 Sesekali terdengar suara jauh dari kanibal...")
                    print("⚡ Berlari semakin cepat dengan semangat escape...")
                    print("🌊 Akhirnya sampai di pantai yang sepi dan aman!")
                    print("⛵ Menemukan perahu kecil tersembunyi di balik batu...")
                    print("💨 Cepat-cepat berlayar sebelum kanibal tahu!")
                    print("\n🎉 Berhasil meninggalkan pulau dengan cepat!")
                    print("😅 Kanibal tidak sempat mengejar sampai ke pantai!")
                    print("\n✅ SELAMAT! Escape cepat menyelamatkan nyawa!")
                    print(f"   {nama} lolos dengan kecepatan dan keberanian! 🎊")
                    
                elif keputusan_aman2 == "3":
                    print(f"\n{nama} tidak tahu harus berbuat apa dan hanya berdiam diri di area pohon...")
                    print("⏳ Hari demi hari berlalu tanpa rencana konkret...")
                    print("🍲 Makanan yang dikumpulkan awalnya mulai habis...")
                    print("💧 Cadangan air semakin menipis karena keliru mengaturnya...")
                    print("😩 Tubuh semakin lemas karena malnutrisi dan kelelahan...")
                    print("👀 Kanibal masih sering lewat di sekitar area pohon...")
                    print("😟 Rasa khawatir dan stress membuat sulit tidur...")
                    print("🌙 Seminggu berlalu... dua minggu berlalu... ketiga minggu...")
                    print("💔 Harapan mulai sirna tanpa ada progress escape...")
                    print("😪 Akhirnya pingsan karena kelaparan dan dehidrasi berat...")
                    print("💤 Tidak bangun lagi di bawah pohon yang sama...")
                    print("\n❌ GAME OVER! Kehabisan sumber daya!")
                    print(f"   {nama} meninggal dalam keadaan lemah di bawah pohon. SELAMAT TINGGAL! 💀")
                    
                else:
                    print("\n❌ Keputusan tidak valid! Suara Anda menarik perhatian...")
                    print(f"   {nama} tertangkap oleh kanibal. GAME OVER! 💀")
                
            elif tempat_sembunyi == "c":
                print(f"\n{nama} melari menuju kolam air dengan rawa!")
                print("💦 Memasuki air yang dingin dan lumpur yang lembek...")
                print("🌊 Menggunakan rawa sebagai penghalang alami...")
                print("🦗 Kupu-kupu dan serangga terbang-terbang...")
                print("✔️  Menyembunyikan diri di antara tebu dan rumput air!")
                print("🤐 Berdiri diam sambil dikepung rawa yang menyerupai labirin!")
                print("✔️  Kanibal tidak berani memasuki rawa yang berbahaya!")
                print("👣 Mereka berlalu tanpa mendekati area rawa ini...")
                print("\n🌅 Setelah dinyatakan aman, Anda keluar dari rawa...")
                print("🧂 Basah kuyup tapi tetap bersemangat untuk bertahan!")
                print("🎣 Di tepi rawa, menemukan kolam ikan yang melimpah!")
                
                print("\n" + "=" * 50)
                print("⭐ KEPUTUSAN PENTING ⭐")
                print("=" * 50)
                print(f"\n{nama} sudah aman keluar dari rawa. Sekarang harus mengambil keputusan:")
                print("1. Tetap di tempat persembunyian Coding - Maksimalkan sumber daya rawa")
                print("2. Melarikan diri Bug - Segera cari dan gunakan perahu!")
                print("3. Ragu-ragu tanpa keputusan - Menunggu tanpa rencana")
                
                keputusan_aman3 = input("\nKeputusan Anda (1, 2, atau 3): ")
                
                if keputusan_aman3 == "1":
                    print(f"\n{nama} memutuskan untuk menjadikan rawa sebagai basis bertahan...")
                    print("🏗️  Memanfaatkan rawa sebagai fortress alami yang aman...")
                    print("📋 Mengorganisir sumber daya - ikan melimpah, air tawar tersedia...")
                    print("🔬 Mengamati pola kanibal dari balik tebu yang lebat...")
                    print("💪 Membangun kekuatan dengan makanan bergizi dari ikan rawa...")
                    print("🎯 Merencanakan escape detail dengan persiapan matang...")
                    print("🛠️  Mengumpulkan material untuk membuat perahu kuat dari bambu...")
                    print("\n✔️  Setelah maksimal persiapan selesai...")
                    print("⛵ Perahu bambu yang tangguh siap berlayar!")
                    print("🎊 Meninggalkan pulau dengan percaya diri penuh!")
                    print("\n✅ SELAMAT! Strategi bertahan di rawa sangat berhasil!")
                    print(f"   {nama} escape dengan sumber daya rawa yang berlimpah! 💪🎊")
                    
                elif keputusan_aman3 == "2":
                    print(f"\n{nama} langsung bergerak cari dan ambil perahu untuk escape...")
                    print("⚡ Keluar dari rawa dan mulai research lokasi perahu...")
                    print("🗺️  Mengikuti tanda-tanda dan petunjuk alam menuju perahu...")
                    print("🏃 Berlari dengan hati-hati menghindari jalur kanibal...")
                    print("😨 Beberapa kali hampir ketahuan tapi terhindar dengan cepat...")
                    print("🌊 Akhirnya mencapai pantai dan menemukan perahu!")
                    print("⛵ Cepat-cepat naik dan berlayar menggunakan tenaga maksimal!")
                    print("💨 Air bercipratan saat menjauh dari pantai...")
                    print("\n🎉 Berhasil escape dari rawa dan pulau misterius!")
                    print("😅 Kanibal berteriak di pantai tapi sudah terlalu jauh!")
                    print("\n✅ SELAMAT! Keputusan cepat menyelamatkan nyawa!")
                    print(f"   {nama} lolos dari pulau dengan aksi cepat! ⛵🎊")
                    
                elif keputusan_aman3 == "3":
                    print(f"\n{nama} tidak tahu apa yang harus dilakukan dan hanya berdiam diri di tepi rawa...")
                    print("⏳ Hari-hari berlalu dengan rasa khawatir dan ketidakpastian...")
                    print("🐟 Ikan di rawa ada tapi tidak ada yang mengatur untuk ditangkap...")
                    print("💧 Air tersedia tapi tanpa perencanaan bergizi yang baik...")
                    print("🦟 Nyamuk dan serangga rawa menyerang terus-menerus...")
                    print("😩 Tubuh makin lemah dan sakit dari gigitan dan infeksi...")
                    print("🤒 Demam tinggi menyerang karena penyakit dari lingkungan rawa...")
                    print("😴 Kesadaran mulai berkurang karena sakit yang parah...")
                    print("🌊 Air di sekitar menjadi tempat berkembang bakteri berbahaya...")
                    print("😪 Akhirnya kehilangan kesadaran dan tidak terbangun lagi...")
                    print("\n❌ GAME OVER! Kehabisan sumber daya dan sakit menimpa!")
                    print(f"   {nama} meninggal karena penyakit dan kelemahan di rawa. SELAMAT TINGGAL! 💀")
                    
                else:
                    print("\n❌ Keputusan tidak valid! Kanibal menemukan jejakmu di rawa!")
                    print(f"   {nama} tertangkap di rawa. GAME OVER! 💀")
                
            else:
                print("\n❌ Pilihan tempat sembunyi tidak valid!")
                print(f"   {nama} terlalu lama mencari dan ketahuan oleh kanibal!")
                print(f"   {nama} tidak berhasil melarikan diri. GAME OVER! 💀")
                
        else:
            print("\n❌ Pilihan aksi tidak valid! Orang kanibal menemukan Anda!")
            print(f"   {nama} tertangkap oleh orang kanibal. GAME OVER! 💀")
    
    else:
        print("\n❌ Pilihan tidak valid! Anda terlalu lama mempertimbangkan dan orang kanibal menemukan Anda!")
        print(f"   {nama} tidak berhasil melarikan diri. GAME OVER! 💀")
    
if __name__ == "__main__":
    game_utama()